### ISSUE TITLE
Can't make on Ubuntu 16.04 (gnutls/gnutls.h: no such file or directory)

### ISSUE THREAD

**Issue by TimotheeChauvin** [dlenski/openconnect#135] opened 2018-11-14 14:27 UTC
I have run:
```
$ sudo apt-get install \
    build-essential gettext autoconf automake libproxy-dev \
    libxml2-dev libtool vpnc-scripts pkg-config \
    libgnutls-dev # may be named libgnutls28-dev on some recent Debian/Ubuntu-based distros
$ git clone https://github.com/dlenski/openconnect.git
```
(by the way, why isn't there the "https:" part in README.md?)
```
$ cd openconnect
$ ./autogen.sh
$ ./configure
```
All of which worked. **Then an error occurred with ```$ make```**:
```
$ make
make  all-recursive
make[1]: Entering directory '/home/utilisateur/Documents/apps/openconnect'
New version: v7.08-157-ge5fe063
  CC       libopenconnect_la-version.lo
  CC       libopenconnect_la-ssl.lo
In file included from ssl.c:41:0:
openconnect-internal.h:56:10: fatal error: gnutls/gnutls.h: No such file or directory
 #include <gnutls/gnutls.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:918: recipe for target 'libopenconnect_la-ssl.lo' failed
make[1]: *** [libopenconnect_la-ssl.lo] Error 1
make[1]: Leaving directory '/home/utilisateur/Documents/apps/openconnect'
Makefile:675: recipe for target 'all' failed
make: *** [all] Error 2
```

As suggested in issues #33 and #45, I installed libgnutls28-dev alongside libgnutls-dev (alongside, because removing libgnutls-dev also removes libgnutls28-dev).

I got a very similar error:
```
$ make
make  all-recursive
make[1]: Entering directory '/home/utilisateur/Documents/apps/openconnect'
  CC       libopenconnect_la-ssl.lo
In file included from ssl.c:41:0:
openconnect-internal.h:56:10: fatal error: gnutls/gnutls.h: No such file or directory
 #include <gnutls/gnutls.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:921: recipe for target 'libopenconnect_la-ssl.lo' failed
make[1]: *** [libopenconnect_la-ssl.lo] Error 1
make[1]: Leaving directory '/home/utilisateur/Documents/apps/openconnect'
Makefile:678: recipe for target 'all' failed
make: *** [all] Error 2
```

I don't know if there's any link but I got some warnings in the output of ```$ ./configure```:
```
$ ./configure
[...]
checking for LIBLZ4... no
configure: WARNING:
***
*** lz4 not found.
*** 
[...]
checking for gssapi.h... no
configure: WARNING: Cannot find <gssapi/gssapi.h> or <gssapi.h>
configure: WARNING: Building without GSSAPI support
[...]
```

I'm using:
- Ubuntu 16.04.5 LTS
- openconnect version e5fe063a087385c5b157ad7a9a3fa874181f6e3b
```
$ openconnect --version
OpenConnect version v7.06
Using GnuTLS. Features present: PKCS#11, RSA software token, HOTP software token, TOTP software token, System keys, DTLS

$ dpkg -l | grep gnutls
ii  libcurl3-gnutls:amd64                         7.47.0-1ubuntu2.11                           amd64        easy-to-use client-side URL transfer library (GnuTLS flavour)
ii  libgnutls-dev:amd64                           3.4.10-4ubuntu1.4                            amd64        GNU TLS library - development files
ii  libgnutls-openssl27:amd64                     3.4.10-4ubuntu1.4                            amd64        GNU TLS library - OpenSSL wrapper
rc  libgnutls26:amd64                             2.12.23-12ubuntu2.8                          amd64        GNU TLS library - runtime library
ii  libgnutls28-dev:amd64                         3.4.10-4ubuntu1.4                            amd64        dummy transitional package for GNU TLS library - development files
ii  libgnutls30:amd64                             3.4.10-4ubuntu1.4                            amd64        GNU TLS library - main runtime library
ii  libgnutls30:i386                              3.4.10-4ubuntu1.4                            i386         GNU TLS library - main runtime library
ii  libgnutlsxx28:amd64                           3.4.10-4ubuntu1.4                            amd64        GNU TLS library - C++ runtime library
ii  libneon27-gnutls:amd64                        0.30.1-3build1                               amd64        HTTP and WebDAV client library (GnuTLS enabled)
```

Thanks for your help!

**Comment by chessai** [comment] 2018-11-15 22:11
I have the exact same issue. Just discovered today, when attempting to rebuild openconnect after having deleted the binary.

**Comment by dlenski** [comment] 2018-11-24 21:50
> (by the way, why isn't there the "https:" part in README.md?)

Derp. Fixing, thanks.

I haven't had any problems like this on Ubuntu 16.04. Did you try wiping the build directory (`make distclean; git clean -fx` should do it) and then rerunning `./autogen.sh && ./configure`?

**Comment by chessai** [comment] 2018-11-24 22:56
Yes, i did. I also deleted the openconnect directory and re-cloned, still the same issue

**Comment by TimotheeChauvin** [comment] 2018-11-25 07:33
The same for me (I also re-cloned). In both cases I get the same warnings in the output of ```$ ./configure``` and the first error message after ```$ make```.

**Comment by TimotheeChauvin** [comment] 2018-11-28 12:35
So I have reinstalled it in a more standard location: ```/usr/local```.
Now everything works, albeit with a few warnings:
```
$ cd /usr/local
$ sudo git clone https://github.com/dlenski/openconnect.git
$ cd openconnect
$ sudo ./autogen.sh
$ sudo ./configure
```
-> same warnings as before
```
$ sudo make
```
-> warning:
```
auth-globalprotect.c: In function ‘gpst_login’:
auth-globalprotect.c:469:3: warning: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Wunused-result]
   asprintf(&vpninfo->urlpath, "%s/prelogin.esp?tmp=tmp&clientVer=4100&clientos=
   ^
```

```
$ sudo make install
$ sudo ldconfig
```

Is this what I should have done from the outset?
(And @chessai does it work for you?)

**Comment by chessai** [comment] 2018-11-28 12:38
I will try this when I get to work, where I use an Ubuntu machine. At home I use NixOS, where I just install this with nix. See https://github.com/dlenski/openconnect/blob/84d342c657cb7483ba72318d93b9a6a4bffaa275/README.md#nix

**Comment by dlenski** [comment] 2019-01-05 03:05
Closing since it's not clearly reproducible. Now that [openconnect v8.00 is out](http://lists.infradead.org/pipermail/openconnect-devel/2019-January/005178.html), we shouldn't have so many GP users needing to build from source.

**Closed by dlenski** 2019-01-05 03:05 UTC
Labels: build help

**Comment by L-F-S** [comment] 2020-03-10 21:55
Hi, I'm having the exact same issue with openconnect 8.

**Comment by dlenski** [comment] 2020-03-10 22:17
Please read the README.
