### ISSUE TITLE
resolv.conf doesn't get updated

### ISSUE THREAD

**Issue by peshoicov** [dlenski/openconnect#127] opened 2018-10-03 10:57 UTC
When I run the vpn client - it runs OK, but it doesn't update the `/etc/resolv.conf` file and I get this in the console:

```...
<13>Oct  3 13:54:27 dns-resolver: ATTENTION: You have modified /etc/resolv.conf. Leaving it untouched...
<13>Oct  3 13:54:27 dns-resolver: You can find my version in /etc/resolv.conf.netconfig
```

And indeed my `/etc/resolv.conf` stays the same, which results in that I don't have access to the internal services we use.
If I add manually the content from the other file - `/etc/resolv.conf.netconfig` - then all is fine. But of course - the idea is the VPN client to update the resolv.conf file, and at the end to revert it to it's original state, no?

So - what am I missing?

**Comment by dlenski** [comment] 2018-10-03 15:11
What OS are you using? What version of `vpnc-script`?

**Comment by peshoicov** [comment] 2018-10-09 08:19
Opensuse Thumbleweed
vpnc version 0.5.3

**Comment by dlenski** [comment] 2018-10-09 21:34
`vpnc-script` is (somewhat confusingly) not the same as vpnc; it's a script that's required by both `vpnc` [and by `openconnect` to configure the routing and DNS settings](http://www.infradead.org/openconnect/vpnc-script.html) of a VPN connection.

I don't think this issue has anything in particular to do with `openconnect`, and certainly not with GP support. It's likely a problem with the vpnc-script` and how it's interacting with your OS.

It appears that this message is telling you that _because_ you have made _manual_ modifications to `/etc/resolv.conf`, `dns-resolver` is refusing to make automatic changes to it…

```
<13>Oct  3 13:54:27 dns-resolver: ATTENTION: You have modified /etc/resolv.conf. Leaving it untouched...
```

**Comment by vwbusguy** [comment] 2018-10-22 18:04
Actually, I'm seeing this now on Fedora.  I'm using the `openconnect` command and it used to update resolv.conf but no longer does automatically after doing a recent `git pull` and recompiling.

**Comment by vwbusguy** [comment] 2018-10-25 23:45
In Fedora, the vpnc-script hasn't seen a real update in over a year (just a rebuild of the same code for Fedora 28 and Fedora 29).  https://koji.fedoraproject.org/koji/packageinfo?packageID=19217

It's possible that there's some other factor, but up until recently (I do a git pull/rebuild of this repo every couple of months or so) resolv.conf was updated automatically and now it isn't.

**Comment by urbim** [comment] 2018-11-06 15:05
@vwbusguy I'm having the same issue on Fedora 29. Have you resolved the issue in any way?

**Comment by peshoicov** [comment] 2018-11-07 13:18
Nope. I reinstalled and now, with fresh system, I don't have problems.
(Now I'm on Opensuse Thumbleweed again.)

**Comment by vwbusguy** [comment] 2018-11-12 19:11
@urbim, Unfortunately, no. The VPN connection works, but I now have to manually update the resolve.conf each time I connect. This used to be automagic. It stopped after I updated and built against this repo which was coincidentally around the same time I upgraded to Fedora 29 and I don't remember if it was similarly broken in Fedora 28.

**Comment by vwbusguy** [comment] 2018-11-12 19:13
I should also note that the resolve.conf is being updated normally everywhere else when I switch networks. It is only broken for me when connecting over openconnect (through this repo). Once I manually update the resolve.conf, everything else is normal.

**Comment by hippymulehead** [comment] 2018-11-16 00:08
I'm having the same issue in Fedora 29.  run openconnect and it connects and I see with -v that it gets the name servers but resolve.conf never gets updated.  If I do it manually it works just fine.  Other OSs are working fine, same settings.

**Comment by dlenski** [comment] 2018-11-25 16:06
I do not use the distributions specifically mentioned in this issue. I doesn't seem to be a problem with openconnect _per se_, but with the vpnc-script.

You will probably attract more eyeballs by posting on the [openconnect-devel mailing list](http://www.infradead.org/openconnect/mail.html) or the [upstream gitlab.com/openconnect/openconnect](https://gitlab.com/openconnect/openconnect).

**Comment by vwbusguy** [comment] 2018-12-05 20:23
It looks like there is actually an update for Fedora 29's vnc-script that may be related.  it's in updates-testing now, but I haven't had a chance to pull it down and try it yet: https://koji.fedoraproject.org/koji/buildinfo?buildID=1168430

**Comment by vwbusguy** [comment] 2018-12-05 20:32
It appears that in Fedora 29, vpnc-script calls resolvectl, which then reports the DNS info but doesn't actually appear to be updating the DNS.  There were also significant default changes in the /etc/nsswitch conf file between 29 and previous, so it may be that those who upgraded to Fedora 29 don't get the new defaults, which affects how vpnc-script attempts to update resolv.conf.  I haven't tested any of this yet, but if that's the case, then this issue may be specific to Fedora users who upgraded to Fedora 29 from a previous version.

**Comment by urbim** [comment] 2018-12-06 07:34
@vwbusguy I pulled down the update to vpnc-script you mentioned and it seems to be working now. Btw, I installed Fedora 29 from scratch and had the same problem so the issue isn't just with users who upgraded from previous versions.

**Comment by vwbusguy** [comment] 2018-12-06 12:53
Same here - I updated the vpnc-script from updates-testing and now the resolv.conf gets updated in openconnect again.  I'd like t thank @dlenski for his patience in handling this ticket.  It seems that he was right that openconnect isn't the issue, but Fedora 29's vpnc-script implementation was.

**Comment by dlenski** [comment] 2019-01-05 03:03
Thanks to @vwbusguy for the useful summary. Looks like we can close this.

**Closed by dlenski** 2019-01-05 03:03 UTC
