### ISSUE TITLE
Building for Windows with msys2 and MinGW32

### ISSUE THREAD

**Issue by jacobruager** [dlenski/openconnect#90] opened 2018-02-21 16:48 UTC
Hi! I hope it is alright to submit this as an issue.

At our work, we have some use for openconnect. A new client of ours (and possibly more soon) now use GlobalProtect with SSL (and not IPSec). I noticed your version of openconnect with gp support. 

I have been able to successfully build it on Ubuntu and Fedora with the listed dependencies. However, we only use Windows, so I thought it would be great to build it here with MinGW, as with the original openconnect client. 

I use msys2 with MinGW32, and the required dependencies. I can build the original openconnect client fine as well on Windows with the above configuration. 

However, I cannot seem to build this particular version. The autogen.sh and ./configure parts work fine, but it fails during make. Below you can see the output:
```
JACOBR-SURFACE+JacobRuager@JacobR-Surface MINGW32 ~/openconnect
$ make
make  all-recursive
make[1]: Entering directory '/home/JacobRuager/openconnect'
New version: v7.08-265-gae481214
  CC       libopenconnect_la-version.lo
  CC       libopenconnect_la-ssl.lo
In file included from ssl.c:41:0:
openconnect-internal.h:382:2: error: unknown type name 'in_addr_t'
  in_addr_t esp_magic; /* GlobalProtect magic ping address (network-endian) */
  ^~~~~~~~~
make[1]: *** [Makefile:910: libopenconnect_la-ssl.lo] Error 1
make[1]: Leaving directory '/home/JacobRuager/openconnect'
make: *** [Makefile:668: all] Error 2
```

As far as I can tell, there are some parts in the code, that are not written in a way like the rest of openconnect, to support compiling with MinGW and Windows. I would love to assist with testing and getting it to work, and think that many other would benefit from getting this client to work!

If you would like any other information, let me know!

**Comment by dlenski** [comment] 2018-02-22 08:44
> I use msys2 with MinGW32, and the required dependencies. I can build the original openconnect client fine as well on Windows with the above configuration.
> …
> As far as I can tell, there are some parts in the code, that are not written in a way like the rest of openconnect, to support compiling with MinGW and Windows.

Thanks for clarifying that you _can_ build the base/upstream openconnect in mingw32, but _not_ this fork… that's an important jumping-off point :+1: 

> ```
> openconnect-internal.h:382:2: error: unknown type name 'in_addr_t'
>  in_addr_t esp_magic; /* GlobalProtect magic ping address (network-endian) */
> ```

In order to support GP, we have to manually construct ICMP packets to get them in the exact format that the gateway requires to activate ESP support.

Yeah, this has also caused problems in BSD and MacOS, since the header files for the IP/ICMP headers are OS-dependent.

It appears that you'll have to include `winsock2.h` and use [the `in_addr` structure](https://msdn.microsoft.com/en-us/library/windows/desktop/ms738571(v=vs.85).aspx), or something similar, to build the IP/ICMP packets on Windows. Then you'll have to add the appropriate `#ifdef`s to use the Windows version vs. the Unix-y versions in `gpst.c`.

**Comment by dlenski** [comment] 2018-02-22 08:51
Actually… since you're building under MinGW/msys2, rather than the "native" Win32 API…

It appears that you need to `#include <apra/inet.h>` to get the `in_addr_t` typedef under MinGW/msys2:

https://sourceforge.net/p/mingw/msys2-runtime/ci/3bbb8258bc4fdf8d915fd6d81aaa9dfec0993c3b/tree/winsup/cygwin/include/arpa/inet.h

Maybe it'll "just work" if you do this?

**Comment by dlenski** [comment] 2018-02-22 14:05
Even easier… try this patch, which simply defines the `esp_magic` value as the equivalent `uint32_t` type on Windows. I'm guessing you're going to run into a whole lot more compilation errors with all the other IP/ICMP header objects in `esp.c`, but with this change you _should_ at least be able to build openconnect-gp _without ESP support enabled_.

```diff
diff --git a/openconnect-internal.h b/openconnect-internal.h
index f42d6ec..e22e67e 100644
--- a/openconnect-internal.h
+++ b/openconnect-internal.h
@@ -379,7 +379,11 @@ struct openconnect_info {
     struct esp esp_out;
     int enc_key_len;
     int hmac_key_len;
+#ifdef _WIN32
+    uint32_t esp_magic;  /* GlobalProtect magic ping address (network-endian) */
+#else
     in_addr_t esp_magic; /* GlobalProtect magic ping address (network-endian) */
+#endif
 
     int tncc_fd; /* For Juniper TNCC */
     const char *csd_xmltag;
```

**Comment by horar** [comment] 2018-02-22 14:20
Just a note from me - building on mingw we don't have "arpa/inet.h" etc.
Looks like the first hint with winsock2.h should be our way (IMHO)...

**Comment by dlenski** [comment] 2018-02-22 14:42
@horar wrote:
>Just a note from me - building on mingw we don't have "arpa/inet.h" etc.
>Looks like the first hint with winsock2.h should be our way (IMHO)...

Gotcha.

I expect that after patching the (trivial) issue of `in_addr_t` (it's just an alias for `uint32_t` on POSIX, essentially), you'll run into the more significant issues with the fact that Win32 API doesn't appear to have predefined header structure for IP/ICMP… or maybe it does and I don't know where to find 'em?

**Comment by jacobruager** [comment] 2018-02-22 15:21
Hi again - thank you for the quick responses!

To clarify, I did try to build using mingw32 under msys2. 
msys2 allows you to configure and make using mingw64, mingw32 or a variant of something similar to cygwin. 

Out of curiosity, I tried to build using the cygwin variant. This won't configure with GnuTLS, which is strange, since I installed the necessary libraries for this variant. So instead I will focus on mingw32.

Did a bit of research, and as horar mentions, there are currently some dependencies which are not found under mingw. Getting it to work with winsock2.h would probably be the best way to go.

In openconnect-internal.h, I have made the minor change, so that for win32 it will use uint32_t instead. 
This currently gives the errors below. As you mentioned, it does give trouble regarding esp.c.

In terms of disabling ESP support, I am not fully sure how to do this during ./configure? There does not seem to be any parameters I can specify to disable this. Is there another way I should do this?

```
$ make
make  all-recursive
make[1]: Entering directory '/home/JacobRuager/mingw32/openconnect'
New version: v7.08-265-gae481214-dirty
  CC       libopenconnect_la-version.lo
  CC       libopenconnect_la-ssl.lo
  CC       libopenconnect_la-http.lo
  CC       libopenconnect_la-http-auth.lo
  CC       libopenconnect_la-auth-common.lo
  CC       libopenconnect_la-library.lo
  CC       libopenconnect_la-compat.lo
  CC       libopenconnect_la-lzs.lo
  CC       libopenconnect_la-mainloop.lo
  CC       libopenconnect_la-script.lo
  CC       libopenconnect_la-ntlm.lo
  CC       libopenconnect_la-digest.lo
  CC       libopenconnect_la-oncp.lo
  CC       libopenconnect_la-lzo.lo
  CC       libopenconnect_la-auth-juniper.lo
  CC       libopenconnect_la-esp.lo
In file included from esp.c:31:0:
C:/msys32/mingw32/include/netinet/ip_icmp.h:45:2: error: unknown type name 'u_int32_t'
  u_int32_t ira_addr;
  ^~~~~~~~~
C:/msys32/mingw32/include/netinet/ip_icmp.h:46:2: error: unknown type name 'u_int32_t'
  u_int32_t ira_preference;
  ^~~~~~~~~
C:/msys32/mingw32/include/netinet/ip_icmp.h:53:2: error: unknown type name 'u_char'
  u_char icmp_type;  /* type of message, see below */
  ^~~~~~
C:/msys32/mingw32/include/netinet/ip_icmp.h:54:2: error: unknown type name 'u_char'
  u_char icmp_code;  /* type sub code */
  ^~~~~~
C:/msys32/mingw32/include/netinet/ip_icmp.h:55:2: error: unknown type name 'u_short'
  u_short icmp_cksum;  /* ones complement cksum of struct */
  ^~~~~~~
C:/msys32/mingw32/include/netinet/ip_icmp.h:64:2: error: unknown type name 'u_char'
  u_char icmp_type;  /* type of message, see below */
  ^~~~~~
C:/msys32/mingw32/include/netinet/ip_icmp.h:65:2: error: unknown type name 'u_char'
  u_char icmp_code;  /* type sub code */
  ^~~~~~
C:/msys32/mingw32/include/netinet/ip_icmp.h:66:2: error: unknown type name 'u_short'
  u_short icmp_cksum;  /* ones complement cksum of struct */
  ^~~~~~~
C:/msys32/mingw32/include/netinet/ip_icmp.h:68:3: error: unknown type name 'u_char'
   u_char ih_pptr;   /* ICMP_PARAMPROB */
   ^~~~~~
C:/msys32/mingw32/include/netinet/ip_icmp.h:69:18: error: field 'ih_gwaddr' has incomplete type
   struct in_addr ih_gwaddr; /* ICMP_REDIRECT */
                  ^~~~~~~~~
C:/msys32/mingw32/include/netinet/ip_icmp.h:83:4: error: unknown type name 'u_char'
    u_char irt_num_addrs;
    ^~~~~~
C:/msys32/mingw32/include/netinet/ip_icmp.h:84:4: error: unknown type name 'u_char'
    u_char irt_wpa;
    ^~~~~~
C:/msys32/mingw32/include/netinet/ip_icmp.h:85:4: error: unknown type name 'u_int16_t'
    u_int16_t irt_lifetime;
    ^~~~~~~~~
C:/msys32/mingw32/include/netinet/ip_icmp.h:109:14: error: field 'idi_ip' has incomplete type
    struct ip idi_ip;
              ^~~~~~
C:/msys32/mingw32/include/netinet/ip_icmp.h:113:3: error: unknown type name 'u_int32_t'
   u_int32_t id_mask;
   ^~~~~~~~~
esp.c: In function 'esp_send_probes_gp':
esp.c:154:49: error: invalid application of 'sizeof' to incomplete type 'struct ip'
  struct pkt *pkt = malloc(sizeof(*pkt) + sizeof(struct ip) + ICMP_MINLEN + sizeof(magic) + vpninfo->pkt_trailer);
                                                 ^~~~~~
esp.c:156:51: error: dereferencing pointer to incomplete type 'struct ip'
  struct icmp *icmph = (void *)(pkt->data + sizeof(*iph));
                                                   ^~~~
esp.c:176:21: error: invalid application of 'sizeof' to incomplete type 'struct ip'
   pkt->len = sizeof(struct ip) + ICMP_MINLEN + sizeof(magic);
                     ^~~~~~
esp.c:183:23: error: 'IP_DF' undeclared (first use in this function)
   iph->ip_off = htons(IP_DF); /* don't fragment, frag offset = 0 */
                       ^~~~~
esp.c:183:23: note: each undeclared identifier is reported only once for each function it appears in
esp.c: In function 'esp_catch_probe_gp':
esp.c:222:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make[1]: *** [Makefile:1008: libopenconnect_la-esp.lo] Error 1
make[1]: Leaving directory '/home/JacobRuager/mingw32/openconnect'
make: *** [Makefile:668: all] Error 2
```

**Comment by dlenski** [comment] 2018-02-22 15:51
> In terms of disabling ESP support, I am not fully sure how to do this during ./configure? There does not seem to be any parameters I can specify to disable this. Is there another way I should do this?

As a quick hack, this patch…

```diff
diff --git a/configure.ac b/configure.ac
index 0762b06..55e3422 100644
--- a/configure.ac
+++ b/configure.ac
@@ -517,6 +517,7 @@ AM_CONDITIONAL(OPENCONNECT_OPENSSL, [ test "$ssl_library" = "OpenSSL" ])
 AM_CONDITIONAL(OPENCONNECT_ESP, [ test "$esp" != "" ])
 AM_CONDITIONAL(OPENCONNECT_DTLS, [ test "$dtls" != "" ])
 
+esp=
 if test "$esp" != ""; then
     AC_DEFINE(HAVE_ESP, 1, [Build with ESP support])
 fi
```

… then `./configure` should give:

```
…
BUILD OPTIONS:
  …
  ESP support:            no
```

**Comment by dwmw2** [comment] 2018-02-22 15:58
My mingw doesn't have `EBADMSG` either.

**Comment by dwmw2** [comment] 2018-02-22 16:00
FWIW minw32 works fairly easily in Fedora; all the dependencies are there and it's just a case of running `mingw32-configure`. It's even in the `.gitlab-ci.yml` setup:
```
  - dnf install -y git autoconf automake libtool python gettext
    mingw64-gnutls mingw64-openssl mingw64-libxml2 mingw64-zlib
    mingw64-gcc wine.i686 make
  - mount -t binfmt_misc binfmt_misc /proc/sys/fs/binfmt_misc
  - echo ':DOSWin:M::MZ::/usr/bin/wine:' > /proc/sys/fs/binfmt_misc/register
  - ./autogen.sh
  - mingw64-configure CFLAGS=-g
  - make -j4
  - make VERBOSE=1 -j4 check
```

**Comment by dlenski** [comment] 2018-02-22 16:43
@dwmw2 wrote:

> My mingw doesn't have EBADMSG either.

Really? I picked it because it's supposed to be bog-standard POSIX… :man_facepalming: 

> FWIW minw32 works fairly easily in Fedora; all the dependencies are there and it's just a case of running mingw32-configure.

Didn't realize it was that easy to cross-build. Excellent.

**Comment by jacobruager** [comment] 2018-02-22 17:31
@dwmw2 Quickly tested your commands on a Fedora 27 Desktop 64-bit box. I can confirm that cross-building this way is also an option, and produces that same errors as on Windows with msys2 and mingw32 or mingw64. 👍 
Also, the EBADMSG error shows up on the Fedora box on my site as well.

Just tested running without ESP on Windows box. Unfortutately it still doesn't work:

```
$ make
make  all-recursive
make[1]: Entering directory '/home/JacobRuager/mingw32/openconnect'
  CC       libopenconnect_la-ssl.lo
  CC       libopenconnect_la-http.lo
  CC       libopenconnect_la-http-auth.lo
  CC       libopenconnect_la-auth-common.lo
  CC       libopenconnect_la-library.lo
  CC       libopenconnect_la-compat.lo
  CC       libopenconnect_la-lzs.lo
  CC       libopenconnect_la-mainloop.lo
  CC       libopenconnect_la-script.lo
  CC       libopenconnect_la-ntlm.lo
  CC       libopenconnect_la-digest.lo
  CC       libopenconnect_la-oncp.lo
  CC       libopenconnect_la-auth-juniper.lo
  CC       libopenconnect_la-esp.lo
  CC       libopenconnect_la-esp-seqno.lo
  CC       libopenconnect_la-gnutls-esp.lo
  CC       libopenconnect_la-auth.lo
  CC       libopenconnect_la-cstp.lo
  CC       libopenconnect_la-dtls.lo
  CC       libopenconnect_la-gnutls-dtls.lo
  CC       libopenconnect_la-oath.lo
  CC       libopenconnect_la-gpst.lo
gpst.c: In function 'gpst_mainloop':
gpst.c:946:23: warning: this statement may fall through [-Wimplicit-fallthrough    ]
   vpninfo->dtls_state = DTLS_CONNECTED;
gpst.c:947:2: note: here
  case DTLS_CONNECTED:
  ^~~~
gpst.c:1120:6: warning: this statement may fall through [-Wimplicit-fallthrough    ]
   if (vpninfo->dtls_state != DTLS_CONNECTED &&
      ^
gpst.c:1124:2: note: here
  case KA_DPD:
  ^~~~
  CC       libopenconnect_la-auth-globalprotect.lo
  CC       libopenconnect_la-yubikey.lo
  CC       libopenconnect_la-stoken.lo
  CC       libopenconnect_la-gnutls.lo
  CC       libopenconnect_la-gnutls_tpm.lo
  CC       libopenconnect_la-tun-win32.lo
  CC       libopenconnect_la-sspi.lo
  CCLD     libopenconnect.la
.libs/libopenconnect_la-library.o:library.c:(.rdata+0x590): undefined reference    to `esp_close_secret'
.libs/libopenconnect_la-library.o:library.c:(.rdata+0x598): undefined reference    to `esp_send_probes_gp'
.libs/libopenconnect_la-library.o:library.c:(.rdata+0x59c): undefined reference    to `esp_catch_probe_gp'
collect2.exe: error: ld returned 1 exit status
make[1]: *** [Makefile:770: libopenconnect.la] Error 1
make[1]: Leaving directory '/home/JacobRuager/mingw32/openconnect'
make: *** [Makefile:668: all] Error 2
```

As far as I can tell, those three functions are found in the esp.c file, and there are necessary references.
I think the best option for now is to go with finding out how to convert it so that it supports winsock2.h for win32. 

Then the rest should make should just fall into place. I will look at the code and see if I have any luck setting this up. I am not fully skilled with C, but hopefully I can figure something out. If you guys find out anything else, I would love to know!

**Comment by dlenski** [comment] 2018-02-23 11:46
> Just tested running without ESP on Windows box. Unfortutately it still doesn't work:
>

The reference to the ESP functions when ESP is disabled is a bug. :facepalm:

I thought I already fixed it, but clearly not. Will do

**Comment by jacobruager** [comment] 2018-02-24 19:39
Great to hear! 

I also managed to build openconnect-gp with mingw32. There were three necessary things to actually build it. It is quite a "quick and dirty" way of doing it, but at least it managed to build.

At the top of esp.c file, having an #ifdef like so will fix the problems regarding not having netinet:
```
#ifdef _WIN32 /*To support win32 for gp*/
#include <winsock2.h>
#include <ws2tcpip.h>
#define	ICMP_MINLEN	8		/* abs minimum  */
#define ICMP_ECHO	8		/* Echo Request */
#define	IP_DF 0x4000			/* dont fragment flag */
#define	IP_MF 0x2000			/* more fragments flag */
struct ip {
	u_char	ip_hl:4;		/* header length */
	u_char  ip_v:4;			/* version */
	u_char	ip_tos;			/* type of service */
	short	ip_len;			/* total length */
	u_short	ip_id;			/* identification */
	short	ip_off;			/* fragment offset field */
	u_char	ip_ttl;			/* time to live */
	u_char	ip_p;			/* protocol */
	u_short	ip_sum;			/* checksum */
	struct	in_addr ip_src,ip_dst;	/* source and dest address */
};
struct icmp_ra_addr
{
  uint32_t ira_addr;
  uint32_t ira_preference;
};
struct icmp
{
  uint8_t  icmp_type;	/* type of message, see below */
  uint8_t  icmp_code;	/* type sub code */
  uint16_t icmp_cksum;	/* ones complement checksum of struct */
  union
  {
    u_char ih_pptr;		/* ICMP_PARAMPROB */
    struct in_addr ih_gwaddr;	/* gateway address */
    struct ih_idseq		/* echo datagram */
    {
      uint16_t icd_id;
      uint16_t icd_seq;
    } ih_idseq;
    uint32_t ih_void;

    /* ICMP_UNREACH_NEEDFRAG -- Path MTU Discovery (RFC1191) */
    struct ih_pmtu
    {
      uint16_t ipm_void;
      uint16_t ipm_nextmtu;
    } ih_pmtu;

    struct ih_rtradv
    {
      uint8_t irt_num_addrs;
      uint8_t irt_wpa;
      uint16_t irt_lifetime;
    } ih_rtradv;
  } icmp_hun;
#define	icmp_pptr	icmp_hun.ih_pptr
#define	icmp_gwaddr	icmp_hun.ih_gwaddr
#define	icmp_id		icmp_hun.ih_idseq.icd_id
#define	icmp_seq	icmp_hun.ih_idseq.icd_seq
#define	icmp_void	icmp_hun.ih_void
#define	icmp_pmvoid	icmp_hun.ih_pmtu.ipm_void
#define	icmp_nextmtu	icmp_hun.ih_pmtu.ipm_nextmtu
#define	icmp_num_addrs	icmp_hun.ih_rtradv.irt_num_addrs
#define	icmp_wpa	icmp_hun.ih_rtradv.irt_wpa
#define	icmp_lifetime	icmp_hun.ih_rtradv.irt_lifetime
  union
  {
    struct
    {
      uint32_t its_otime;
      uint32_t its_rtime;
      uint32_t its_ttime;
    } id_ts;
    struct
    {
      struct ip idi_ip;
      /* options and then 64 bits of data */
    } id_ip;
    struct icmp_ra_addr id_radv;
    uint32_t   id_mask;
    uint8_t    id_data[1];
  } icmp_dun;
#define	icmp_otime	icmp_dun.id_ts.its_otime
#define	icmp_rtime	icmp_dun.id_ts.its_rtime
#define	icmp_ttime	icmp_dun.id_ts.its_ttime
#define	icmp_ip		icmp_dun.id_ip.idi_ip
#define	icmp_radv	icmp_dun.id_radv
#define	icmp_mask	icmp_dun.id_mask
#define	icmp_data	icmp_dun.id_data
};
#else
#include <netinet/ip.h>
#include <netinet/ip_icmp.h>
#endif
```
Under the openconnect-internal.h, I changed the in_addr_t to uint32_t.
Lastly, under gpst.c, I removed the sys/wait.h, since this is not supported under mingw32. However, I am not sure what needs to be replaced here.

Next up, I want to connect to our client and see what it reports. I will probably test this during the next week.

**Comment by dlenski** [comment] 2018-02-25 05:19
Well done.

So there are no standard headers under Windows that will allow you to build IP/ICMP packets …?

If not, perhaps this whole thing should be factored out into a separate `win32-packets.h` or something like that.

**Comment by dlenski** [comment] 2018-02-25 08:00
@jacobruager, please pull the latest version, 42166de3f. I added a few patches based on your findings to factor out the packet headers on win32 and more cleanly implement what you described.

> ```
> .libs/libopenconnect_la-library.o:library.c:(.rdata+0x590): undefined reference    to `esp_close_secret'
> .libs/libopenconnect_la-library.o:library.c:(.rdata+0x598): undefined reference    to `esp_send_probes_gp'
> .libs/libopenconnect_la-library.o:library.c:(.rdata+0x59c): undefined reference    to `esp_catch_probe_gp'
> collect2.exe: error: ld returned 1 exit status
> make[1]: *** [Makefile:770: libopenconnect.la] Error 1
> make[1]: Leaving directory '/home/JacobRuager/mingw32/openconnect'
> make: *** [Makefile:668: all] Error 2
> ```
> As far as I can tell, those three functions are found in the esp.c file, and there are necessary references.
> I think the best option for now is to go with finding out how to convert it so that it supports winsock2.h for win32.

Unfortunately I can't reproduce this. When I disable ESP support manually, and rebuild _from scratch_, these functions are not referenced anywhere and they should not cause a linker error.

Are you still having this problem?

**Comment by jacobruager** [comment] 2018-02-26 09:29
From what I gathered, the IP / ICMP packets were simply made from some constant values and known datatypes, thus no additional Windows packages, libraries etc. were necessary. This would probably require some more investigation. I do not fully know what is included with winsock2 for Windows.

I will try pulling, and see if I can reproduce the issue regarding disabling ESP. 

I also did some testing connection to our client - it did not want to fully connect, and constantly mentioned that ESP was not possible, so it switches to SSL / HTTPS. I will send some dumps later this week which will probably explain it better.

**Comment by dlenski** [comment] 2018-02-26 11:25
> From what I gathered, the IP / ICMP packets were simply made from some constant values and known datatypes, thus no additional Windows packages, libraries etc. were necessary. This would probably require some more investigation. I do not fully know what is included with winsock2 for Windows.

You're right… I was just curious if there was a way to do it without duplicating the Linux header files' contents.

> I also did some testing connection to our client - it did not want to fully connect, and constantly mentioned that ESP was not possible, so it switches to SSL / HTTPS. I will send some dumps later this week which will probably explain it better.

Right. Need to see the log with `openconnect -vvvv --dump` for this. You might want to also fire up Wireshark and verify that the ESP ping packets are (a) getting sent and (b) exactly match the [contents which I describe here](https://github.com/dlenski/openconnect/blob/globalprotect/PAN_GlobalProtect_protocol_doc.md#esp-over-udp). It's possible that there's some tricky detail about the structure of the IP/ICMP packet headers which wasn't handled properly under Windows.

But if it's working with SSL/HTTPS-only… that's great progress :+1:.

**Comment by bhank** [comment] 2018-03-03 18:46
I successfully built a windows executable on Fedora (on an Amazon EC2 instance) and used it to connect to a GlobalProtect VPN.

My `errno.h` did not have `EBADMSG`, so I copied `errno.h` from the mingw32 install on my Windows machine; it was identical except for the addition of `EBADMSG` and nine other constants.

I renamed `win32-ipcimp.h` to `win32-ipicmp.h` (presumably a typo), and was able to build.

When I tried to connect, I got the `Running the 'HIP Report' script on this platform is not yet implemented` message. I saw the notes saying that the HIP Report is not always actually required, so I changed it to `return 0` there, and I was able to connect and send traffic across the VPN.

Nicely done, thanks!

**Comment by dlenski** [comment] 2018-03-04 07:57
> I renamed win32-ipcimp.h to win32-ipicmp.h (presumably a typo), and was able to build.

Thanks, fixed. :man_facepalming: 

> When I tried to connect, I got the `Running the 'HIP Report' script on this platform is not yet implemented` message. I saw the notes saying that the HIP Report is not always actually required, so **I changed it to `return 0` there**, and I was able to connect and send traffic across the VPN.

Thanks, fixed this one too.

**Comment by jacobruager** [comment] 2018-03-04 16:49
I have had a busy week, but a lot seems to have been done for the last few days! Hopefully I will have some time to check your progress and feedback during this upcoming week.

Really great work!

**Comment by jacobruager** [comment] 2018-03-14 08:41
I managed to test the build I made, as mentioned in my previous post - and it works! 

There are however, some things I needed to do, in order to connect:
1. I have to manually add a route with "route add" in the command prompt, pointing to the assigned IP-address given by the GlobalProtect VPN-server.
2. I made this build with ESP. At first when it tries ESP, I cannot connect at all. When it switches to HTTPS, I can connect. Building without ESP is probably the best solution.
3. For some reason, I have to run the client with --dump -vvv. If not, then it crashes during establishing a secure connection.

Hope this will help others, trying to build a Windows version!

**Comment by dlenski** [comment] 2018-03-15 08:23
>There are however, some things I needed to do, in order to connect:
>1. I have to manually add a route with "route add" in the command prompt, pointing to the assigned IP-address given by the GlobalProtect VPN-server.
>2. I made this build with ESP. At first when it tries ESP, I cannot connect at all. When it switches to HTTPS, I can connect. Building without ESP is probably the best solution.
>3. For some reason, I have to run the client with --dump -vvv. If not, then it crashes during establishing a secure connection.
>
>Hope this will help others, trying to build a Windows version!

1. This sounds like a `vpnc-script` problem, not an `openconnect` problem.
2. So ESP is not working. And you're sure that you _can_ connect with ESP using the official client in the same network environment? @bhank, is ESP working on your build?
3. Hmmm… can you get a stack track for where it's crashing?

**Comment by jacobruager** [comment] 2018-03-15 12:26
You are right, this seems very much to be a problem with the vpnc-script.

I also investigated if our client uses ESP, and they do not - so it may very well be that ESP i working fine. Unfortunately, I do not work with any other clients for now, who uses ESP.

I also wanted to clarify regarding the crash - it is not an application crash (sorry I did not explain this better). It tries to establish a TLS connection, which fails and stops the connection / exits the openconnect application. Adding --dump -vvv as parameter does not produce this issue. I am not sure how I can track why this occurs, and since it does not occur under the --dump parameter, I cannot get detailed information on the issue.

**Comment by bhank** [comment] 2018-03-18 02:36
> @bhank, is ESP working on your build?

Yes, I think so. I didn't disable it, and upon connecting it says `ESP session established with server` followed by `ESP tunnel connected; exiting HTTPS mainloop.`

It works for me with or without `--dump -vvv`.

My only current issue is that Ctrl-C is not properly handled; it shuts down immediately rather than cleaning up first. I tried using `SetConsoleCtrlHandler` (as described in [this stackoverflow answer](https://stackoverflow.com/questions/16826097/equivalent-to-sigint-posix-signal-for-catching-ctrlc-under-windows-mingw#16826362)) to catch Ctrl-C and write `OC_CMD_CANCEL` to `sig_cmd_fd` like in the existing SIGINT handler, but that didn't do the trick; my handler runs, but openconnect just keeps running, and doesn't clean up or shut down.

**Comment by dlenski** [comment] 2018-03-18 05:14
> My only current issue is that Ctrl-C is not properly handled; it shuts down immediately rather than cleaning up first. I tried using SetConsoleCtrlHandler (as described in this stackoverflow answer) to catch Ctrl-C and write OC_CMD_CANCEL to sig_cmd_fd like in the existing SIGINT handler, but that didn't do the trick; my handler runs, but openconnect just keeps running, and doesn't clean up or shut down.

Hmmm… any reason that you think this is specific to the GP protocol support? Does the same binary correctly close non-GP sessions on Ctrl-C? Or does a build of the upstream master handle this correctly?

**Comment by bhank** [comment] 2018-03-18 12:59
No, I have no reason to think this doesn't affect the upstream -- I should be complaining about it there.

**Comment by dlenski** [comment] 2018-05-21 08:51
@jacobruager, you're the first person to contribute useful feedback and code for openconnect-gp on Windows.

If you have any interest/need to tackle the problem of getting the HIP report script to run on Windows, see #106 and [this comment](https://github.com/dlenski/openconnect/issues/106#issuecomment-390592650). :grin:

**Comment by dlenski** [comment] 2018-06-25 08:29
Closing this because openconnect + GP is now building successfully on mingw32, upstream.

See https://gitlab.com/dwmw2/openconnect/pipelines

**Closed by dlenski** 2018-06-25 08:29 UTC
Labels: bug
