### ISSUE TITLE
Authentication failed: Invalid User

### ISSUE THREAD

**Issue by OmegaZero** [dlenski/openconnect#29] opened 2017-05-03 21:33 UTC
# Problem description
I can connect with the Windows GlobalProtect client fine but upon trying this is just keeps saying invalid user.

1. I ran openconnect-gp as follows: `/usr/sbin/openconnect --protocol=gp vpn.foo.com -vvv --dump --authenticate -u foouser`

# Operating system and openconnect-gp version

openconnect-gp version:
```
OpenConnect version v7.08-1ubuntu5
Using GnuTLS. Features present: PKCS#11, RSA software token, HOTP software token, TOTP software token, Yubikey OATH, System keys, DTLS
```

operating system
```
Linux ubuntu 4.8.0-36-generic #36~16.04.1-Ubuntu SMP Sun Feb 5 09:39:57 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

# GlobalProtect VPN information

```
Please enter your username and password.
Password: 
POST https://vpn.foo.com/ssl-vpn/login.esp
Attempting to connect to server 123.45.67.78:443
Connected to 123.45.67.78:443
SSL negotiation with vpn.foo.com
Connected to HTTPS on vpn.foo.com
> POST /ssl-vpn/login.esp HTTP/1.1
> Host: vpn.foo.com
> User-Agent: PAN GlobalProtect
> X-Pad: 0000000000000000000000000000000000000000000000000000
> Content-Type: application/x-www-form-urlencoded
> Content-Length: 140
> 
> jnlpReady=jnlpReady&ok=Login&direct=yes&clientVer=4100&prot=https:&server=vpn.foo.com&computer=ubuntu&user=foouser&passwd=foopass
Got HTTP response: HTTP/1.1 512 Custom error
Server: 
Date: Wed, 03 May 2017 21:10:05 GMT
Content-Type: text/html
Content-Length: 111
Connection: keep-alive
ETag: "foonumbers"
Pragma: no-cache
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
x-private-pan-sslvpn: auth-failed
Expires: Thu, 19 Nov 1981 08:52:00 GMT
X-FRAME-OPTIONS: DENY
Set-Cookie: PHPSESSID=foofoofoofoo; secure; HttpOnly
Set-Cookie: PHPSESSID=foofoofoofoo; secure; HttpOnly
Set-Cookie: PHPSESSID=foofoofoofoo; secure; HttpOnly
HTTP body length:  (111)
< 
< var respStatus = "Error";
< var respMsg = "Authentication failed: Invalid User";
< thisForm.inputStr.value = "";
< 
Unexpected 512 result from server
Invalid username or password.
Please enter your username and password.
```

**Comment by dlenski** [comment] 2017-05-03 22:04
That's odd.

Two dumb questions:

1. You're sure you're using the same user name?
2. You're sure the Windows username doesn't have a domain in front of it? Something like `CORP\foouser` instead of just `foouser`?

One slightly subtler one: is the server you're trying to connect to the [portal server or the gateway server](https://github.com/dlenski/openconnect/blob/HEAD/README.md#portal-vs-gateway-servers)? If it's the portal server, try the instructions in that link for enumerating the gateway servers, and use one of those instead.

**Comment by OmegaZero** [comment] 2017-05-04 14:17
1) Positive.  I even tried a co-worker of mine's and his said the same thing
2) I thought that might be the case so I tried domain\foouser but it gave the same error.  I tried enclosing this in quotes as well.

As far as the gateway or portal server I only have the one address.  The script (which I had to install apt-get install python-requests to get it to work with my python 2.7 btw) also only shows only the single gateway.

Our company uses the GlobalProtect Duo(phone app) for dual authentication - could this have something to do with it?

**Comment by dlenski** [comment] 2017-05-04 16:13
> Our company uses the GlobalProtect Duo(phone app) for dual authentication - could this have something to do with it?

I added support for challenge-based 2FA in #12, although I have not yet rebuilt the Ubuntu/.deb packages to include this support. However, the error that you're getting is _not_ the same error that the server returns when it expects a second authentication factor—as far as I know.

In order to fix this issue, we'd need to figure out what's different about the protocol used by your client/server (I know _absolutely nothing_ beyond what I've figured out from reverse engineering and other users' reports):

1. You could run [mitmproxy](//github.com/mitmproxy/mitmproxy) to capture the traffic between the client and server. I have some scripts that make this relatively straightforward.
2. You could search through the Windows client's log files and grep for `login.esp` and figure out what's different about the login request sent by the Windows client, compared to what openconnect-gp is sending:

```
POST https://vpn.foo.com/ssl-vpn/login.esp
> POST /ssl-vpn/login.esp HTTP/1.1
> Host: vpn.foo.com
> User-Agent: PAN GlobalProtect
> X-Pad: 0000000000000000000000000000000000000000000000000000
> Content-Type: application/x-www-form-urlencoded
> Content-Length: 140
> 
> jnlpReady=jnlpReady&ok=Login&direct=yes&clientVer=4100&prot=https:&server=vpn.foo.com&computer=ubuntu&user=foouser&passwd=foopass
```

**Comment by OmegaZero** [comment] 2017-05-04 17:24
Alright well I checked out the logs.  First thing I noticed is that on mine there is a prelogin.esp which is done before the login.esp.  Here's the log line for that...

IPADDR=vpn.foo.com,PORT=443,URL=/global-protect/prelogin.esp,POST=1,PROXY_AUTO=1,PROXY_CFGURL=NULL,PROXY=NULL,PROXY_BYPASS=NULL,PROXY_USER=NULL,PROXY_PASS=****,VERIFY_CERT=1,ADDITIONAL_CHECK=1,SCEP_CERT=,oid=

it responds with

(T3172) 05/01/17 19:37:40:316 Debug(2615): HTTP_RPC, len=286, result is 
<?xml version="1.0" encoding="UTF-8" ?>
<prelogin-response>
<status>Success</status>
<ccusername></ccusername>
<autosubmit>false</autosubmit>
<msg></msg>
<auth...
(T3172) 05/01/17 19:37:40:316 Debug(4391): prelogin to portal result is 
<?xml version="1.0" encoding="UTF-8" ?>
<prelogin-response>
<status>Success</status>
<ccusername></ccusername>
<autosubmit>false</autosubmit>
<msg></msg>
<authentication-message>Enter login credentials</authentication-message>
<panos-version>7.1.4-h2</panos-version></prelogin-response>

**Comment by dlenski** [comment] 2017-05-04 17:33
The Windows client always does the prelogin request… as far as I can tell it is useless and does nothing at all other than tell the Windows to prompt for credentials, potentially pre-populating the username field if there was a client certificate 

What you really need to figure out here is… what does the **login.esp** request look like? What are the URL parameters passed to it?

**Comment by OmegaZero** [comment] 2017-05-04 18:16
The only line I see is this from PanGPS.log

IPADDR=vpn.foo.com,PORT=443,URL=/ssl-vpn/login.esp,POST=1,PROXY_AUTO=1,PROXY_CFGURL=NULL,PROXY=NULL,PROXY_BYPASS=NULL,PROXY_USER=NULL,PROXY_PASS=****,VERIFY_CERT=0,ADDITIONAL_CHECK=1,SCEP_CERT=,oid=

is there another file that would have a more detailed output of what the post variables are?

**Comment by dlenski** [comment] 2017-05-04 18:34
> EDIT: Actually I just grepped the log file directory and PanGPS is the only file that returned any line with login.esp

The Windows log format is kind of an ugly mess and it shows the request body/parameters in a different place from the URL for some reason.

Just grep for `passwd` or `user` or `jnlpReady` since those strings should definitely appear in the same URL parameter blob. You'll also need to be sure you've turned on the highest logging level.

**Comment by dlenski** [comment] 2017-05-05 19:31
> As far as the gateway or portal server I only have the one address. The script (which I had to install apt-get install python-requests to get it to work with my python 2.7 btw) also **only shows only the single gateway.**

@OmegaZero, hold on a sec… I just noticed this. The `get-globalprotect-config.py` script _works_?!?!

That script accesses `/global-protect/getconfig.esp`, which accepts the _exact same arguments_ as `/ssl-vpn/login.esp` — in every case that I've seen. If `/global-protect/getconfig.esp` works, then `/ssl-vpn/login.esp` should work too.

Please try changing the request URL in the Python script as follows:

```diff
-login = 'https://{}/global-protect/getconfig.esp'.format(args.portal)
+login = 'https://{}/ssl-vpn/login.esp'.format(args.portal)
```

Then re-run it. What do you get? The same error 512, or a blob of XML that looks like this?

```xml
<?xml version="1.0" encoding="utf-8"?><jnlp><application-desc><argument>(null)</argument><argument>***</argument><argument>***</argument><argument>Gateway-N</argument><argument>daniel.lenski</argument><argument>LDAP-auth</argument><argument>vsys1</argument><argument>***</argument><argument>(null)</argument><argument></argument><argument></argument><argument></argument><argument>tunnel</argument><argument>-1</argument><argument>4100</argument><argument></argument><argument></argument><argument></argument></application-desc></jnlp>
```

**Comment by OmegaZero** [comment] 2017-05-06 01:18
The same 512 error

Username: foouser
Password: 
Traceback (most recent call last):
  File "./get-globalprotect-config2.py", line 48, in <module>
    res.raise_for_status()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 512 Server Error: Custom error for url: https://vpn.foo.com/ssl-vpn/login.esp

**Comment by dlenski** [comment] 2017-05-06 02:01
Well, I haven't seen a server before where you couldn't send the same parameters to `/global-protect/getconfig.esp` and `/ssl-vpn/login.esp`.

I suggest running [mitmproxy](https://mitmproxy.org/) and using it to capture the login request, in order to make progress here.

**Comment by dlenski** [comment] 2017-05-06 02:07
You might want to try submitting a request to `login.esp` with *all* the form fields filled in… does that make any difference? I omit some of them in openconnect because they don't seem to do anything

https://gist.github.com/dlenski/5046e5f934ac111e8d8718fc10c25703#login-request

**Comment by dlenski** [comment] 2017-05-09 17:10
@OmegaZero, any more progress or findings on this issue?

**Comment by OmegaZero** [comment] 2017-05-10 20:11
I apologize as I haven't had a chance to work on this more.  I'm currently rebuilding a laptop that I will use to test this more, should be able to get back to in in a couple days.

I did find out that our GlobalProtect requires Anti-Virus and the computer to be on the domain - do you know if you login request handles that by default?

**Comment by dlenski** [comment] 2017-05-11 16:07
> I did find out that our GlobalProtect requires Anti-Virus…

PAN calls this "Host Intrusion Protection." All GP VPNs seem to request this from the client, but (a) they don't seem to do anything bad if the client doesn't upload its HIP information, so I haven't bothered to support it in openconnect, and (b) they request it _after login_ so it can't be the problem here.

> and the computer to be on the domain - do you know if you login request handles that by default and/or where that would be "checked" by the auth?

I don't know what "be on the domain" means. If your VPN is checking for valid logins by some mechanism that's outside of the normal GP login request… then it's certainly not being handled by OpenConnect.

IT/VPN administrators will tell you about lots of stuff that's "required" by particular client software (e.g. the official Windows client) without them actually knowing anything about the underlying VPN protocol.

Really the only way to tell what's going on will be to get a MITM log of the VPN traffic and figure out how the login request from your computer differs from the ones that I've been reverse-engineered.

**Comment by divad** [comment] 2017-05-17 13:12
"Be on the domain" is Windows-admin speak for the machine has joined an Active Directory domain, e.g. it has become a member of the Kerberos realm and has a computer object, or rather, has kerberos UPN records for the local host. I don't see how that has anything to do with this bug, though (or the protocol).

**Comment by dlenski** [comment] 2017-05-17 17:06
> I don't see how that has anything to do with this bug, though (or the protocol).

I don't either, but I don't understand Kerberos login that well. (Perhaps Kerberos isn't communicating the login request correctly between the Linux box and the Windows machine, for instance.)

I see nothing unusual or unexpected in the login flow from what @OmegaZero has shared so far. It's a bit useless to speculate on what is different about his VPN until I see a more detailed mitmproxy log…

**Comment by dlenski** [comment] 2017-05-24 16:22
@OmegaZero, any follow-up? If not I will close this due to not being able to reproduce it.

**Comment by OmegaZero** [comment] 2017-05-24 16:38
It's actually kind of funny that you responded today since I was in the process of setting the computer back up for testing :)  Sorry for the delay - been very busy

Anyways, I have mitmproxy installed although I'm not sure how to go about setting it up/running it while I do the openconnect call?  Do you have a script or something?

**Comment by OmegaZero** [comment] 2017-05-24 16:44
BTW in case somebody else needs to setup an environment for this, I just used a the Ubuntu 16.04 LTS Live CD.  Commands I ran are

# Need this because the live CD apparently has a bug that cant update the apt  DB
sudo chmod -R a+rX,u+w /var/cache/app-info/xapian/default
# Need this for the vpnc-scripts requirement
sudo add-apt-repository universe
#Add repository for this project
sudo add-apt-repository  ppa:lenski/openconnect-gp
#Run this again because bugs
sudo chmod -R a+rX,u+w /var/cache/app-info/xapian/default
sudo apt-get update
sudo apt-get install vpnc-scripts libopenconnect5 openconnect

#And you should be all set up!

**Comment by dlenski** [comment] 2017-05-24 16:53
> Anyways, I have mitmproxy installed although I'm not sure how to go about setting it up/running it while I do the openconnect call? Do you have a script or something?

Easiest way, roughly:

1. Run your Linux system on the same local network as your Windows/Mac system.
2. Run `mitmproxy -p 8080` on the Linux system.
3. Configure the Windows system to use the Linux box as a SOCKS proxy (under "Internet Options | Lan Settings")
4. Follow the instructions [in the mitmproxy docs|http://docs.mitmproxy.org/en/stable/certinstall.html#quick-setup] to install the mitmproxy certificate so that the Windows system will trust certificates signed by it.
5. **(You may need to completely kill and restart the GlobalProtect service on Windows, or even reboot.)**
6. Run GlobalProtect client on Windows. It should automatically use the proxy… at least, the above instructions were good enough for me. GlobalProtect is horribly buggy when running through a proxy, but it _should_ be good enough to capture the authentication traffic.
7. Inspect the flows captured by mitmproxy and compare them to [my log from reverse engineering the protocol](https://github.com/dlenski/openconnect/blob/globalprotect/PAN_GlobalProtect_protocol_doc.md#login-request).

> sudo add-apt-repository ppa:lenski/openconnect-gp

The version of the package in the PPA is out-of-date at this point. Rebuilding the package is kind of a pain, so I haven't done it recently.

However, unless you're using challenge-based authentication the Ubuntu package should be good enough to get you started.

Just be aware that if we identify a problem… I may need you to build from source to get the latest version. It's not too hard :smile:

**Comment by OmegaZero** [comment] 2017-05-28 13:13
FYI so I set all this up and after testing it I think they problem could be the Duo app on the phone after all.  I put in a ticket to my domain admin to ask him some things about the Duo and once I hear back from him (and probably do some more testing) I should know for sure.

**Comment by hypnot0ad** [comment] 2017-06-08 08:08
Its entirely possible that if you are having an issue with prelogon, and your machine requires being connected to the domain, that prelogon has been configure to perform machine authentication with a certificate. If you fail the machine auth check, you will fail vpn auth. Just a guess...

Might pay to check with the FW admin if this is configured.

I will have this running in a poc in a few weeks if you want me to test anything and your FW admin is a bust.

**Comment by dlenski** [comment] 2017-06-08 14:03
>Its entirely possible that if you are having an issue with prelogon, and your machine requires being connected to the domain, that prelogon has been configure to perform machine authentication with a certificate. If you fail the machine auth check, you will fail vpn auth. Just a guess...
>
>Might pay to check with the FW admin if this is configured.
>
>I will have this running in a poc in a few weeks if you want me to test anything and your FW admin is a bust.

@hypnot0ad, how does the "prelogon" work? Do you have any documentation or understanding of this process? On my VPN at least… it seems to be entirely extraneous.

**Comment by OmegaZero** [comment] 2017-06-08 14:54
Yeah, I think the pre-login is the problem with mine but I don't think it has to do with the machine certificate as much as it does with the Duo app.   On our system we have to login with Duo first, that generates an "OK" in the system and THEN you login.  If I could ever get my domain admin to look into it for me we could make some progress here....

**Comment by dlenski** [comment] 2017-06-09 17:37
I know nothing about Duo (as previously mentioned :joy:) but… can you do the Duo login on the phone app/Windows/wherever you do it, and then do the actual VPN connection on Linux with openconnect?

**Comment by dlenski** [comment] 2017-06-20 00:59
Closing due to inactivity. I haven't got enough information about how Duo and/or GlobalProtect prelogon to make any useful progress on resolving this.

**Closed by dlenski** 2017-06-20 00:59 UTC

**Comment by jrversteegh** [comment] 2017-09-25 20:22
I had this issue on a laptop, but not on my desktop. Turned out to be a missing `vpnc-script`. Not sure if that is the issue here,  but openconnect doesn't complain about a missing vpnc-script in any way and `sudo apt-get install vpnc-scripts` doesn't install it. Not on my Linux Mint box anyway.

**Comment by dlenski** [comment] 2017-09-25 21:13
@jversteegh: This particular issue cannot have anything to do with the vpnc-script.

The authentication to the VPN gateway runs way before the vpnc-script ever touches anything … and the vpnc-script only changes *local* client networking configuration.

**Comment by jrversteegh** [comment] 2017-09-25 22:18
You're right. There **is** an error about the missing vpnc-script, but it was swallowed by my use of `expect`. The `512` then occured while manually trying to debug this and was probably just the result of a 'regular' logon error. Sorry about that.

**Comment by AshrazRashid** [comment] 2017-11-09 19:40
@dlenski  can you help me about DuoAuthProxy using openconnect
error :The service did not report an error.
command C:\Program Files (x86)\Duo Security Authentication Proxy\bin>net start DuoAuthProxy

**Comment by dlenski** [comment] 2017-11-09 19:57
@AshrazRashid: file a new issue and explain in detail what you're doing and how it relates to GlobalProtect support. I have never heard of DuoAuthProxy before.
