### ISSUE TITLE
Unexpected response of size 3 after hostname packet

### ISSUE THREAD

**Issue by ramarnat** [dlenski/openconnect#113] opened 2018-07-18 17:44 UTC
# Problem description

1. I ran openconnect-gp as follows: `openconnect --dump-http-traffic -vvvv  --juniper juniper.server --user=ME --sslkey=./ssl.crt --cookie="DSID=xxxxx"`

I know that your version is a fork for GP, but I did see that there was a fix you made for NC and unexpected response, and for some reason even with that fix in the version I compiled I get the error. I am hoping you know what might be going on. 

```
WARNING: Juniper Network Connect support is experimental.
It will probably be superseded by Junos Pulse support.
Attempting to connect to server xxx:443
Connected to xxx:443
SSL negotiation with juniper.server 
Connected to HTTPS on juniper.server 
Got HTTP response: HTTP/1.1 200 OK
Content-type: application/octet-stream
Pragma: no-cache
NCP-Version: 2
Set-Cookie: DSLastAccess=1531935496; path=/; Secure
Connection: close
SSL negotiation with juniper.server 
Connected to HTTPS on juniper.server 
Got HTTP response: HTTP/1.1 200 OK
Content-type: application/octet-stream
Pragma: no-cache
NCP-Version: 2
Set-Cookie: DSLastAccess=1531935497; path=/; Secure
Connection: close
> 0000: 19 00 00 04 00 00 00 0c 00 65 34 30 37 65 37 32
> 0010: 62 65 36 66 34 bb 01 00 00 00 00
Read 3 bytes of SSL record
< 0000: 00 00 01
Unexpected response of size 3 after hostname packet
Creating SSL connection failed
```
# Operating system and openconnect-gp version

openconnect-gp version:

```
   OpenConnect version v7.08-316-g0e71e624
Using GnuTLS. Features present: PKCS#11, HOTP software token, TOTP software token, System keys, DTLS, ESP
Supported protocols: anyconnect (default), nc, gp
```

operating system

```
    Linux e407e72be6f4 4.9.93-linuxkit-aufs #1 SMP Wed Jun 6 16:55:56 UTC 2018 x86_64 GNU/Linux
```

**Comment by dlenski** [comment] 2018-07-30 01:01
Closing because I don't have any other information to reproduce or continue.

**Closed by dlenski** 2018-07-30 01:01 UTC

**Comment by dkfi** [comment] 2019-01-07 10:49
I'm experiencing the same issue connecting to a Juniper Network Connect Version 7.1-17-Build28099.
Following is some more debugging information which could turn out useful. Hostnames have been obfuscated for privacy matters. 

```bash
root@workstation:~# openconnect --protocol=nc --no-proxy --user=kdu --proxy=http://my-proxy-server:3128 --disable-ipv6 --printcookie --verbose https://juniper-server/dana-na/auth/url_6/welcome.cgi
GET https://juniper-server/dana-na/auth/url_6/welcome.cgi
Attempting to connect to proxy 10.128.0.218:3128
Connected to 10.128.0.218:3128
Requesting HTTP proxy connection to juniper-server:443
Got HTTP response: HTTP/1.1 200 Connection established
SSL negotiation with juniper-server
Connected to HTTPS on juniper-server
Got HTTP response: HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Date: Mon, 07 Jan 2019 10:35:50 GMT
Connection: close
Pragma: no-cache
Cache-Control: no-store
Expires: -1
HTTP body http 1.0 (-1)
SSL socket closed uncleanly
frmLogin
realm [SMS|TOKEN]:SMS
frmLogin
password:
POST https://juniper-server/dana-na/auth/url_6/login.cgi
Requesting HTTP proxy connection to juniper-server:443
Got HTTP response: HTTP/1.1 200 Connection established
SSL negotiation with juniper-server
Connected to HTTPS on juniper-server
Got HTTP response: HTTP/1.1 302 Moved
location: https://juniper-server/dana-na/auth/url_6/welcome.cgi?p=more-cred&id=state_17af3d1d26cdeb64b244840680fa7105
Content-Type: text/html; charset=utf-8
Connection: close
Pragma: no-cache
Cache-Control: no-store
Expires: -1
HTTP body http 1.0 (-1)
SSL socket closed uncleanly
GET https://juniper-server/dana-na/auth/url_6/welcome.cgi?p=more-cred&id=state_17af3d1d26cdeb64b244840680fa7105
Requesting HTTP proxy connection to juniper-server:443
Got HTTP response: HTTP/1.1 200 Connection established
SSL negotiation with juniper-server
Connected to HTTPS on juniper-server
Got HTTP response: HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Date: Mon, 07 Jan 2019 10:36:16 GMT
Connection: close
Pragma: no-cache
Cache-Control: no-store
Expires: -1
HTTP body http 1.0 (-1)
SSL socket closed uncleanly
frmLogin
password#2:
POST https://juniper-server/dana-na/auth/url_6/login.cgi
Requesting HTTP proxy connection to juniper-server:443
Got HTTP response: HTTP/1.1 200 Connection established
SSL negotiation with juniper-server
Connected to HTTPS on juniper-server
Got HTTP response: HTTP/1.1 302 Moved
Set-Cookie: DSASSERTREF=x; path=/; expires=Thu, 01 Jan 1970 22:00:00 GMT; secure
Set-Cookie: DSID=3fae2a42ee5649d5dfc50c3de8dcd19c; path=/; secure
Set-Cookie: DSFirstAccess=1546857386; path=/; secure
Date: Mon, 07 Jan 2019 10:36:26 GMT
location: https://juniper-server/dana/home/starter0.cgi?check=yes
Content-Type: text/html; charset=utf-8
Connection: close
Pragma: no-cache
Cache-Control: no-store
Expires: -1
HTTP body http 1.0 (-1)
SSL socket closed uncleanly
GET https://juniper-server/dana/home/starter0.cgi?check=yes
Requesting HTTP proxy connection to juniper-server:443
Got HTTP response: HTTP/1.1 200 Connection established
SSL negotiation with juniper-server
Connected to HTTPS on juniper-server
Got HTTP response: HTTP/1.1 200 OK
Content-type: text/html; charset=utf-8
Set-Cookie: DSLastAccess=1546857385; path=/; Secure
Connection: close
Pragma: no-cache
Cache-Control: no-store
Expires: -1
HTTP body http 1.0 (-1)
SSL socket closed uncleanly
DSID=3fae2a42ee5649d5dfc50c3de8dcd19c; DSFirst=1546857386; DSLast=1546857385
Requesting HTTP proxy connection to juniper-server:443
Got HTTP response: HTTP/1.1 200 Connection established
SSL negotiation with juniper-server
Connected to HTTPS on juniper-server
Got HTTP response: HTTP/1.1 200 OK
Content-type: application/octet-stream
Pragma: no-cache
NCP-Version: 2
Set-Cookie: DSLastAccess=1546857385; path=/; Secure
Connection: close
Requesting HTTP proxy connection to juniper-server:443
Got HTTP response: HTTP/1.1 200 Connection established
SSL negotiation with juniper-server
Connected to HTTPS on juniper-server
Got HTTP response: HTTP/1.1 200 OK
Content-type: application/octet-stream
Pragma: no-cache
NCP-Version: 2
Set-Cookie: DSLastAccess=1546857386; path=/; Secure
Connection: close
0000: 15 00 00 04 00 00 00 08 00 6b 72 69 73 74 69 61
0010: 6e bb 01 00 00 00 00
Unexpected response of size 3 after hostname packet
Creating SSL connection failed
```
